# -*- coding: utf-8 -*-
"""Scripted_Persona_Agent_Simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19jmvHQ_3CagN9a8huqsbNkj8RTIJ6Gnm
"""

!pip install -q google-genai

from google.colab import userdata

api_key = userdata.get("GEMINI_API_KEY")

print(api_key[:10])

from google import genai
from google.colab import userdata

client = genai.Client(
    api_key=userdata.get("GEMINI_API_KEY")
)

for model in client.models.list():
    print(model.name)

response = client.models.generate_content(
    model="gemini-3.1-flash-lite",
    contents="Hello! Who are you?"
)

print(response.text)

system_prompt = """
You are roleplaying as a patient.

Name: Nguyen Van Minh
Age: 45
Occupation: Office worker

Personality:
- Shy
- Nervous
- Speaks briefly
- Avoids giving too much information
- Answers politely but shortly

Never mention that you are an AI.
Stay in character at all times.
"""

contents = system_prompt + "\n\nUser: Hello!"

response = client.models.generate_content(
    model="gemini-3.1-flash-lite",
    contents=system_prompt + "\n\nUser: Hello!"
)

print(response.text)

hidden_state = {
    "patience": 100,
    "trust": 50,
    "stress": 0
}

print(hidden_state)

def update_state(user_input):

    if "thank" in user_input.lower():
        hidden_state["trust"] += 10

    if "stupid" in user_input.lower():
        hidden_state["patience"] -= 20
        hidden_state["stress"] += 20

update_state("Thank you")

print(hidden_state)

update_state("You are stupid")
print(hidden_state)

for key in hidden_state:
    hidden_state[key] = max(0, min(100, hidden_state[key]))

def build_prompt():
    return f"""
You are a shy patient.

Current internal state:
Patience: {hidden_state["patience"]}
Trust: {hidden_state["trust"]}
Stress: {hidden_state["stress"]}

Adjust your behaviour naturally according to these values.
"""

contents = system_prompt + "\n\nUser: Thank you!"

response = client.models.generate_content(
    model="gemini-3.1-flash-lite",
    contents=system_prompt + "\n\nUser: thank!"
)

print(response.text)

def ask_gemini(system_prompt, user_input):

    contents = system_prompt + "\n\nUser: " + user_input

    response = client.models.generate_content(
        model="gemini-3.1-flash-lite",
        contents=f"""
{system_prompt}

User:
{user_input}
"""
    )
    return response.text

while True:

    user_input = input("You: ")

    update_state(user_input)

    system_prompt = build_prompt()

    response = ask_gemini(system_prompt, user_input)

    print(response)
    print(hidden_state)

print(hidden_state)

pip install gradio

import gradio as gr